#!/bin/ksh
#
# Author: Patrick Brockmann 
# Contact: Patrick.Brockmann@ipsl.jussieu.fr 
# $Date: 2011/09/07 15:03:08 $ 
# $Name: FAST_672_1_0 $
# $Revision: 1.1.1.26 $
# History:
# Modification:
#

#***************************************
# Redirect standard error on standard output
#      and redirect standar output on null
exec 2>&1 1>/dev/null

#***************************************
ferret -server << EOS 

use "$1"     
exit            

EOS

#***************************************

# clean
rm -f ferret.jnl* > /dev/null 2>&1
