#!/bin/ksh
#
# Author: Patrick Brockmann
# Contact: Patrick.Brockmann@cea.fr
# $Date: 2011/09/07 15:03:45 $
# $Name: FAST_672_1_0 $
# $Revision: 1.1.1.4 $
# History:
# Modification:
#
# Usage: echo 29-FEB-1979 09:00 | convert_date
#
# Usage: 
#          yes? def axis/t="12-JAN-2003:00:00:00":"12-JAN-2003:00:00:00":3/units=hours mytaxis
#          yes? let a=t[gt=mytaxis]
#          yes? let b={spawn:"echo `a[l=1],return=tstart,p=5` | convert_date"}
#          yes? list b[i=1], b[i=2] 
#          print "2003-01-12" "00:00"


export LC_ALL=C
gawk '{
	day=substr($1,1,2)
	month=substr($1,4,3)
	year=substr($1,8,4)
	hour=substr($2,1,2)
	minute=substr($2,4,2)

	if (month == "JAN")  
		month="01" ;
	else if (month == "FEB")
		month="02" ;
	else if (month == "MAR")
		month="03" ;
	else if (month == "APR")
		month="04" ;
	else if (month == "MAY")
		month="05" ;
	else if (month == "JUN")
		month="06" ;
	else if (month == "JUL")
		month="07" ;
	else if (month == "AUG")
		month="08" ;
	else if (month == "SEP")
		month="09" ;
	else if (month == "OCT")
		month="10" ;
	else if (month == "NOV")
		month="11" ;
	else if (month == "DEC")
		month="12" ;
		
	printf("%s-%s-%s\n", year, month, day)
	printf("%s:%s\n", hour, minute)
}'
