#!/bin/ksh
#
# Author: Patrick Brockmann
# Contact: Patrick.Brockmann@cea.fr
# History:
# Modification:
#
# Usage: echo ABCDEF | convert_hexa

export LC_ALL=C
gawk --non-decimal-data '{
	a=sprintf("0x%s\n",substr($1,1,2))
	b=sprintf("0x%s\n",substr($1,3,2))
	c=sprintf("0x%s\n",substr($1,5,2))
	#printf("%X\n%X\n%X\n", a, b, c)
	printf("%3.1f\n%3.1f\n%3.1f\n",(100.*a)/255, (100.*b)/255, (100.*c)/255)
}'
